
Liste de tuple

 [
    {
        'match_id': 3,
        'last_name': 'mario',
        'first_name': 'sylainx',
        'gender': 'Masculin',
        'birth_date': '2000-01-01',
        'phone': '84838-2884',
        'nif': '1234',
        'username': 'mrtop',
        'balance': 500.0,
        'status': 'A',
        'is_admin': 0
    },
   
    {'id': 3,
     'last_name': 'mario',
     'first_name': 'sylainx',
     'gender': 'Masculin',
     'birth_date': '2000-01-01',
     'phone': '84838-2884',
     'nif': '1234',
     'username': 'mrtop',
     'balance': 500.0,
     'status': 'A',
     'is_admin': 0
    }, {'id': 3,
     'last_name': 'mario',
     'first_name': 'sylainx',
     'gender': 'Masculin',
     'birth_date': '2000-01-01',
     'phone': '84838-2884',
     'nif': '1234',
     'username': 'mrtop',
     'balance': 500.0,
     'status': 'A',
     'is_admin': 0
    },
    {'id': 3,
     'last_name': 'mario',
     'first_name': 'sylainx',
     'gender': 'Masculin',
     'birth_date': '2000-01-01',
     'phone': '84838-2884',
     'nif': '1234',
     'username': 'mrtop',
     'balance': 500.0,
     'status': 'A',
     'is_admin': 0
    },
    {'id': 3,
     'last_name': 'mario',
     'first_name': 'sylainx',
     'gender': 'Masculin',
     'birth_date': '2000-01-01',
     'phone': '84838-2884',
     'nif': '1234',
     'username': 'mrtop',
     'balance': 500.0,
     'status': 'A',
     'is_admin': 0
    },
    {'id': 3,
     'last_name': 'mario',
     'first_name': 'sylainx',
     'gender': 'Masculin',
     'birth_date': '2000-01-01',
     'phone': '84838-2884',
     'nif': '1234',
     'username': 'mrtop',
     'balance': 500.0,
     'status': 'A',
     'is_admin': 0
    },
    {'id': 3,
     'last_name': 'mario',
     'first_name': 'sylainx',
     'gender': 'Masculin',
     'birth_date': '2000-01-01',
     'phone': '84838-2884',
     'nif': '1234',
     'username': 'mrtop',
     'balance': 500.0,
     'status': 'A',
     'is_admin': 0
    },
]
